<?php

require_once dirname( __DIR__ ) . '/rust-gateway.php';
$rust_gateway_request_path = wp_rust_gateway_current_request_path( '/wp-includes/blocks/require-static-blocks.php' );
if ( '/wp-includes/blocks/require-static-blocks.php' === $rust_gateway_request_path
	&& wp_rust_gateway_try_proxy( $rust_gateway_request_path ) ) {
	exit;
}

// This file was autogenerated by tools/gutenberg/copy-gutenberg-build.js, do not change manually!
// Returns folder names for static blocks necessary for core blocks registration.
return array(
	'accordion-heading',
	'accordion-panel',
	'audio',
	'buttons',
	'code',
	'column',
	'columns',
	'details',
	'embed',
	'freeform',
	'group',
	'html',
	'list-item',
	'math',
	'missing',
	'more',
	'nextpage',
	'paragraph',
	'preformatted',
	'pullquote',
	'quote',
	'separator',
	'social-links',
	'spacer',
	'table',
	'terms-query',
	'text-columns',
	'verse',
);
